### ISSUE TITLE
oficial wifi and bluetooth dont works ;(

### ISSUE THREAD

**Issue by InfernalWolf666** [SputnikRocket/ArchLinuxARM-rk3588-installer#4]
oficial wifi and bluetooth dont works ;(

**Comment by SputnikRocket** [comment]
I will look into it, currently away from home at the moment.

**Comment by InfernalWolf666** [comment]
Dear Sir. I express my gratitude for your feedback to me. You can see the solution to this problem from Mr. Joshua Riek in the release of Ubuntu, it seems 1.29. He's the only one who did it right. Then please, if possible, make a GNOME desktop. The rat's desk is terribly inconvenient, I couldn't even change the time, I just can't find it. Thank you, best regards.

**Comment by SputnikRocket** [comment]
thank you. after I will apply the fix in probably the next release, but I cannot test it as I do not have the official wifi/bt module. and an experimental gnome version will mostly likely be available with the release after that.

**Comment by SputnikRocket** [comment]
@InfernalWolf666 Please can you test this for me? this is at least part of Joshua Riek's fix.

```
$ cd /usr/lib/systemd/system/
$ sudo wget https://raw.githubusercontent.com/Joshua-Riek/ubuntu-rockchip/main/overlay/usr/lib/systemd/system/rtl8852be-reload.service
$ sudo systemctl enable rtl8852be-reload.service
```
and reboot. please tell me if it works.

**Comment by InfernalWolf666** [comment]
I have a problem's !  I can't set the correct time, the browser doesn't work.  I entered the command to get pacman keys.  error .  nonsense OS does not respond.  I can't download anything

**Comment by SputnikRocket** [comment]
> I have a problem's ! I can't set the correct time, the browser doesn't work. I entered the command to get pacman keys. error . nonsense OS does not respond. I can't download anything

@InfernalWolf666 after you connect to the internet, do `sudo systemctl enable --now systemd-timesyncd` and wait a few seconds.

**Comment by InfernalWolf666** [comment]
listen bro! And you can take the sources from Joshua Riek or Manjaro...... I mean that all the device trees and the environment are gnome but just in Archlinux with panfrost graphics.

Please look here - https://github.com/manjaro-arm?language=html

Repositories download new versions of programs, beautiful style, but all without drivers

**Comment by SputnikRocket** [comment]
you seem to be unwilling to help me work through your problems. and no, it is not possible to "bolt" distros on top of one another and have them "just work" I would like to keep this as much Arch Linux ARM upstream as possible.
