### ISSUE TITLE
orangepi5不能正常启动

### ISSUE THREAD

**Issue by abel840** [SputnikRocket/ArchLinuxARM-rk3588-installer#5]
我使用sd卡烧写uefi，使用u盘烧写archlinux，板子没有外接sata和nvme，启动卡在pcie初始化host，请问是什么问题呢
rk-pcie fe190000.pcie: failed to initialize host

**Comment by b-rad15** [comment]
I am also facing this same issue on an orange pi 5 plus now after it was working for a while. How did you fix this?

Mine was caused after I was running it off a USB Flash Drive, wrote the Flash Drive's image to eMMC, then rebooted to the eMMC, and now both the eMMC and the USB wont boot. The boot partition and all other kernel files/modules are identical to the source img.

**Comment by SputnikRocket** [comment]
> Mine was caused after I was running it off a USB Flash Drive, wrote the Flash Drive's image to eMMC, then rebooted to the eMMC, and now both the eMMC and the USB wont boot. The boot partition and all other kernel files/modules are identical to the source img.

Can you access the UEFI boot menu and verify that both the USB drive and emmc are both recognized as boot-able  devices?
